const {PORT, MONGODB_URI, REDIS_HOST,
  REDIS_PASSWORD,
  REDIS_PORT, JWT_SECRET, SMTP_PASSWORD, SMTP_USERNAME, SMTP_SERVER, SMTP_PORT, GOOGLE_WEB_CLIENT_ID, CLOUDINARY_API_KEY,
  CLOUDINARY_SECRET_KEY,
  CLOUDINARY_CLOUD_NAME,} = process.env


module.exports = {PORT, MONGODB_URI, REDIS_HOST,
  REDIS_PASSWORD,
  REDIS_PORT, JWT_SECRET, SMTP_PASSWORD, SMTP_USERNAME, SMTP_SERVER, SMTP_PORT, GOOGLE_WEB_CLIENT_ID, CLOUDINARY_API_KEY,
  CLOUDINARY_SECRET_KEY,
  CLOUDINARY_CLOUD_NAME,}